### PR TITLE
 feat: add passive touch events option

### PR DESCRIPTION
**Pull request by stsvilik**

### CODE REVIEW

**Comment by stsvilik** [comment]
Added feature detection and implementation.

**Comment by stsvilik** [comment]
Just out of curiosity did you intentionally left out semicolons? Also having vars comma-delimited makes it hard to debug :)

**Comment by jerrybendy** [comment]
I think it is not necessary to detect if browser  supports `passive` or not. Browsers will ignore the `passive` if they don't support it, don't they?

**Comment by jerrybendy** [comment]
I have looked up the documents of MDN, and I got it IS necessary to detect `passive` supporting. You're right. 

And, whether leave out semicolons or not just a kind of habit, it doesn't matter   😄

**Pull request merged**
