### PR TITLE
no 'tap' event after 'touchhold' event

### PR DESCRIPTION
**Pull request by ghnacker**

### CODE REVIEW

**Comment by jerrybendy** [comment]
Hi @ghnacker ,

Thanks for your PR.

This is a breaking change. If users' code depends on this behavior (a `tap` event bound after a `touchhold`), this could course issues. So we have to change the major version to `v3.0` or add an option to enable this feature. What do you think? which one is better?

**Comment by ghnacker** [comment]
`touchhold.prevent`, `touchhold.notap`, `holdtap` ...

`v-touch-options="{ touchHoldNoTap: true }"`, ...

no idea...

**Comment by jerrybendy** [comment]
Maybe add an option is better 😂

**Comment by jerrybendy** [comment]
There are too many options now, so I choose to release a new major version to make a break change, not add new option. Now it is `v3.0.0`. Thank you.

**Pull request merged**
